In [8]:
import pandas as pd
import numpy as np
df=pd.read_excel("/content/student.xlsx")
df

,student_id,Name,Age,Gender,course,Marks,City,Admission_Date
0,S201,Rahul,20.0,M,BCA,85.0,Bengaluru,2023-12-06 00:00:00
1,S202,Priya,NaN,F,BBA,78.0,Chennai,15/07/2023
2,S203,Arjun,21.0,M,BCA,92.0,Hyderabad,2023-10-08 00:00:00
3,S204,Sneha,19.0,F,MCA,88.0,Mysuru,20/06/2023
4,S205,Kiran,150.0,M,BBA,65.0,Bengaluru,2023-10-08 00:00:00
5,S206,Anjali,22.0,F,BCA,-45.0,Chennai,15/07/2023
6,NaN,Ravi,21.0,M,MCA,95.0,Delhi,2023-01-08 00:00:00
7,S208,NaN,20.0,F,BCA,72.0,Hyderabad,22/08/2023
8,S209,Manju,-19.0,F,BBA,80.0,Bengaluru,2023-10-07 00:00:00
9,S210,Suresh,22.0,M,MCA,89.0,Chennai,2023-05-08 00:00:00
10,S201,Rahul,20.0,M,BBA,85.0,Bengaluru,2023-12-06 00:00:00
11,S212,Divya,21.0,F,NaN,76.0,Mysuru,18/07/2023
12,S213,Naveen,22.0,M,BCA,NaN,Hyderabad,25/08/2023
13,S214,Pooja,20.0,F,BBA,62.0,NaN,2023-12-07 00:00:00

In [9]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   student_id      13 non-null     object
 1   Name            13 non-null     object
 2   Age             13 non-null     float64
 3   Gender          14 non-null     object
 4   course          13 non-null     object
 5   Marks           13 non-null     float64
 6   City            13 non-null     object
 7   Admission_Date  14 non-null     object
dtypes: float64(2), object(6)
memory usage: 1.0+ KB
None

In [10]:
print(df.dtypes)

student_id         object
Name               object
Age               float64
Gender             object
course             object
Marks             float64
City               object
Admission_Date     object
dtype: object

In [11]:
print(df.head())

  student_id   Name    Age Gender course  Marks       City  \
0       S201  Rahul   20.0      M    BCA   85.0  Bengaluru
1       S202  Priya    NaN      F    BBA   78.0    Chennai
2       S203  Arjun   21.0      M    BCA   92.0  Hyderabad
3       S204  Sneha   19.0      F    MCA   88.0     Mysuru
4       S205  Kiran  150.0      M    BBA   65.0  Bengaluru

        Admission_Date
0  2023-12-06 00:00:00
1           15/07/2023
2  2023-10-08 00:00:00
3           20/06/2023
4  2023-10-08 00:00:00

In [12]:
print(df.tail())

   student_id    Name   Age Gender course  Marks       City  \
9        S210  Suresh  22.0      M    MCA   89.0    Chennai
10       S201   Rahul  20.0      M    BBA   85.0  Bengaluru
11       S212   Divya  21.0      F    NaN   76.0     Mysuru
12       S213  Naveen  22.0      M    BCA    NaN  Hyderabad
13       S214   Pooja  20.0      F    BBA   62.0        NaN

         Admission_Date
9   2023-05-08 00:00:00
10  2023-12-06 00:00:00
11           18/07/2023
12           25/08/2023
13  2023-12-07 00:00:00

In [13]:
print(df.isnull())

    student_id   Name    Age  Gender  course  Marks   City  Admission_Date
0        False  False  False   False   False  False  False           False
1        False  False   True   False   False  False  False           False
2        False  False  False   False   False  False  False           False
3        False  False  False   False   False  False  False           False
4        False  False  False   False   False  False  False           False
5        False  False  False   False   False  False  False           False
6         True  False  False   False   False  False  False           False
7        False   True  False   False   False  False  False           False
8        False  False  False   False   False  False  False           False
9        False  False  False   False   False  False  False           False
10       False  False  False   False   False  False  False           False
11       False  False  False   False    True  False  False           False
12       False  False  False   False   False   True  False           False
13       False  False  False   False   False  False   True           False

In [14]:
print(df.isnull().sum())

student_id        1
Name              1
Age               1
Gender            0
course            1
Marks             1
City              1
Admission_Date    0
dtype: int64

In [15]:
print(df.isnull().sum().sum())

6

In [16]:
print(df.duplicated())

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
dtype: bool

In [17]:
print(df.duplicated().sum())

0

In [19]:
df=df.drop_duplicates()
df

,student_id,Name,Age,Gender,course,Marks,City,Admission_Date
0,S201,Rahul,20.0,M,BCA,85.0,Bengaluru,2023-12-06 00:00:00
1,S202,Priya,NaN,F,BBA,78.0,Chennai,15/07/2023
2,S203,Arjun,21.0,M,BCA,92.0,Hyderabad,2023-10-08 00:00:00
3,S204,Sneha,19.0,F,MCA,88.0,Mysuru,20/06/2023
4,S205,Kiran,150.0,M,BBA,65.0,Bengaluru,2023-10-08 00:00:00
5,S206,Anjali,22.0,F,BCA,-45.0,Chennai,15/07/2023
6,NaN,Ravi,21.0,M,MCA,95.0,Delhi,2023-01-08 00:00:00
7,S208,NaN,20.0,F,BCA,72.0,Hyderabad,22/08/2023
8,S209,Manju,-19.0,F,BBA,80.0,Bengaluru,2023-10-07 00:00:00
9,S210,Suresh,22.0,M,MCA,89.0,Chennai,2023-05-08 00:00:00
10,S201,Rahul,20.0,M,BBA,85.0,Bengaluru,2023-12-06 00:00:00
11,S212,Divya,21.0,F,NaN,76.0,Mysuru,18/07/2023
12,S213,Naveen,22.0,M,BCA,NaN,Hyderabad,25/08/2023
13,S214,Pooja,20.0,F,BBA,62.0,NaN,2023-12-07 00:00:00

In [20]:
df["Name"]=df["Name"].fillna("Unknown")
df

,student_id,Name,Age,Gender,course,Marks,City,Admission_Date
0,S201,Rahul,20.0,M,BCA,85.0,Bengaluru,2023-12-06 00:00:00
1,S202,Priya,NaN,F,BBA,78.0,Chennai,15/07/2023
2,S203,Arjun,21.0,M,BCA,92.0,Hyderabad,2023-10-08 00:00:00
3,S204,Sneha,19.0,F,MCA,88.0,Mysuru,20/06/2023
4,S205,Kiran,150.0,M,BBA,65.0,Bengaluru,2023-10-08 00:00:00
5,S206,Anjali,22.0,F,BCA,-45.0,Chennai,15/07/2023
6,NaN,Ravi,21.0,M,MCA,95.0,Delhi,2023-01-08 00:00:00
7,S208,Unknown,20.0,F,BCA,72.0,Hyderabad,22/08/2023
8,S209,Manju,-19.0,F,BBA,80.0,Bengaluru,2023-10-07 00:00:00
9,S210,Suresh,22.0,M,MCA,89.0,Chennai,2023-05-08 00:00:00
10,S201,Rahul,20.0,M,BBA,85.0,Bengaluru,2023-12-06 00:00:00
11,S212,Divya,21.0,F,NaN,76.0,Mysuru,18/07/2023
12,S213,Naveen,22.0,M,BCA,NaN,Hyderabad,25/08/2023
13,S214,Pooja,20.0,F,BBA,62.0,NaN,2023-12-07 00:00:00

In [21]:
df["Age"]=df["Age"].fillna(df["Age"].mean())
df

,student_id,Name,Age,Gender,course,Marks,City,Admission_Date
0,S201,Rahul,20.000000,M,BCA,85.0,Bengaluru,2023-12-06 00:00:00
1,S202,Priya,27.615385,F,BBA,78.0,Chennai,15/07/2023
2,S203,Arjun,21.000000,M,BCA,92.0,Hyderabad,2023-10-08 00:00:00
3,S204,Sneha,19.000000,F,MCA,88.0,Mysuru,20/06/2023
4,S205,Kiran,150.000000,M,BBA,65.0,Bengaluru,2023-10-08 00:00:00
5,S206,Anjali,22.000000,F,BCA,-45.0,Chennai,15/07/2023
6,NaN,Ravi,21.000000,M,MCA,95.0,Delhi,2023-01-08 00:00:00
7,S208,Unknown,20.000000,F,BCA,72.0,Hyderabad,22/08/2023
8,S209,Manju,-19.000000,F,BBA,80.0,Bengaluru,2023-10-07 00:00:00
9,S210,Suresh,22.000000,M,MCA,89.0,Chennai,2023-05-08 00:00:00
10,S201,Rahul,20.000000,M,BBA,85.0,Bengaluru,2023-12-06 00:00:00
11,S212,Divya,21.000000,F,NaN,76.0,Mysuru,18/07/2023
12,S213,Naveen,22.000000,M,BCA,NaN,Hyderabad,25/08/2023
13,S214,Pooja,20.000000,F,BBA,62.0,NaN,2023-12-07 00:00:00

In [24]:
df["Marks"]=df["Marks"].fillna(df["Marks"].mean())
df["Marks"]

0     85.000000
1     78.000000
2     92.000000
3     88.000000
4     65.000000
5    -45.000000
6     95.000000
7     72.000000
8     80.000000
9     89.000000
10    85.000000
11    76.000000
12    70.923077
13    62.000000
Name: Marks, dtype: float64

In [26]:
df.loc[df["Age"]>100,"Age"]=np.nan
df.loc[df["Age"]>100,"Age"]

Series([], Name: Age, dtype: float64)

In [28]:
df["Age"]=df["Age"].fillna(df["Age"].mean())
df["Age"]

0     20.000000
1     27.615385
2     21.000000
3     19.000000
4     18.201183
5     22.000000
6     21.000000
7     20.000000
8    -19.000000
9     22.000000
10    20.000000
11    21.000000
12    22.000000
13    20.000000
Name: Age, dtype: float64

In [29]:
df.loc[df["Marks"]>100,"Marks"]=np.nan
df.loc[df["Marks"]>100,"Marks"]

Series([], Name: Marks, dtype: float64)

In [30]:
df.loc[df["Marks"]<0,"Marks"]=np.nan
df.loc[df["Marks"]<0,"Marks"]

Series([], Name: Marks, dtype: float64)

In [31]:
df["Age"]=df["Age"].astype(int)
df["Age"]

0     20
1     27
2     21
3     19
4     18
5     22
6     21
7     20
8    -19
9     22
10    20
11    21
12    22
13    20
Name: Age, dtype: int64

In [32]:
print(df.describe())

             Age      Marks
count  14.000000  13.000000
mean   18.142857  79.840237
std    10.890060  10.324157
min   -19.000000  62.000000
25%    20.000000  72.000000
50%    20.500000  80.000000
75%    21.750000  88.000000
max    27.000000  95.000000

In [34]:
df["Name"]=df["Name"].str.strip()
df["Name"]

0       Rahul
1       Priya
2       Arjun
3       Sneha
4       Kiran
5      Anjali
6        Ravi
7     Unknown
8       Manju
9      Suresh
10      Rahul
11      Divya
12     Naveen
13      Pooja
Name: Name, dtype: object

In [35]:
df.to_excel("clean_student.excel",index=False)

ValueError: No engine for filetype: 'excel'

In [36]:
print(df["Marks"].min())

62.0

In [38]:
print(df["Marks"].max())

95.0

In [39]:
df=pd.get_dummies(df,columns=["Gender"])
df

,student_id,Name,Age,course,Marks,City,Admission_Date,Gender_F,Gender_M
0,S201,Rahul,20,BCA,85.000000,Bengaluru,2023-12-06 00:00:00,False,True
1,S202,Priya,27,BBA,78.000000,Chennai,15/07/2023,True,False
2,S203,Arjun,21,BCA,92.000000,Hyderabad,2023-10-08 00:00:00,False,True
3,S204,Sneha,19,MCA,88.000000,Mysuru,20/06/2023,True,False
4,S205,Kiran,18,BBA,65.000000,Bengaluru,2023-10-08 00:00:00,False,True
5,S206,Anjali,22,BCA,NaN,Chennai,15/07/2023,True,False
6,NaN,Ravi,21,MCA,95.000000,Delhi,2023-01-08 00:00:00,False,True
7,S208,Unknown,20,BCA,72.000000,Hyderabad,22/08/2023,True,False
8,S209,Manju,-19,BBA,80.000000,Bengaluru,2023-10-07 00:00:00,True,False
9,S210,Suresh,22,MCA,89.000000,Chennai,2023-05-08 00:00:00,False,True
10,S201,Rahul,20,BBA,85.000000,Bengaluru,2023-12-06 00:00:00,False,True
11,S212,Divya,21,NaN,76.000000,Mysuru,18/07/2023,True,False
12,S213,Naveen,22,BCA,70.923077,Hyderabad,25/08/2023,False,True
13,S214,Pooja,20,BBA,62.000000,NaN,2023-12-07 00:00:00,True,False

In [40]:
print(df.head(7))

  student_id    Name  Age course  Marks       City       Admission_Date  \
0       S201   Rahul   20    BCA   85.0  Bengaluru  2023-12-06 00:00:00
1       S202   Priya   27    BBA   78.0    Chennai           15/07/2023
2       S203   Arjun   21    BCA   92.0  Hyderabad  2023-10-08 00:00:00
3       S204   Sneha   19    MCA   88.0     Mysuru           20/06/2023
4       S205   Kiran   18    BBA   65.0  Bengaluru  2023-10-08 00:00:00
5       S206  Anjali   22    BCA    NaN    Chennai           15/07/2023
6        NaN    Ravi   21    MCA   95.0      Delhi  2023-01-08 00:00:00

   Gender_F  Gender_M
0     False      True
1      True     False
2     False      True
3      True     False
4     False      True
5      True     False
6     False      True